#设置端口
server:
  port: 1314
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: AIGOU_CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gy5751320/aigou_config.git
          username: gy5751320
          password: cx5751320