spring:
  application:
    name: AIGOU_PRODUCT
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou
      username: root
      password: cx1320
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8005
mybatis-plus:
  type-aliases-package: com.liuritian.aigou.domain,com.liuritian.aigou.query